repos:

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
        args: ["--fix"] # Enable automatic fixes
        files: ^job_agent/
      - id: ruff-format
        files: ^job_agent/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        exclude: ^migrations/
        args: ["--ignore-words-list=selectin"]
        files: ^job_agent/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.0"
    hooks:
      - id: mypy
        exclude: "alembic"
        entry: mypy
        additional_dependencies:
        - pydantic
        - pydantic[mypy]
        files: ^job_agent/

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.397
    hooks:
      - id: pyright
        exclude: "alembic"
        entry: bash -c 'cd job_agent && uv run pyright'
        files: ^job_agent/